name: Deploy Theme
on:
  push:	
    branches:	
      - ikaruswill/toc
jobs:
  deploy-ikarus-sg:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.3.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: "casper-ikaruswill-toc"
  deploy-tech-ikarus-sg:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: TryGhost/action-deploy-theme@v1.2.1
        with:
          api-url: ${{ secrets.GHOST_TECH_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_TECH_ADMIN_API_KEY }}
          theme-name: "casper-ikaruswill-toc"
